## Numpy array and basics

In [3]:
import numpy as np 

### creating array from list 

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: \n", arr_2d)


1D Array:  [1 2 3 4 5]
2D Array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array 

In [6]:
py_list = [1,2,3]
print("Python List Multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #element-wise multiplication
print("Numpy Array Multiplication: ", np_array * 2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2 
print("\n Numpy operation time: ", time.time() - start)


Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication:  [2 4 6]

 List operation time:  0.13185811042785645

 Numpy operation time:  0.013622522354125977


### Creating array from Scratch

In [9]:
zeros = np.zeros((3,4))
print("Zeros Array: \n", zeros)

ones = np.ones((2,3))
print("Ones Array: \n", ones)

full = np.full((2,2), 7)
print("Full Array: \n", full)

random = np.random.random((3,3))
print("Random Array: \n", random)

sequence = np.arange(0,11,2)
print("Sequence Array:\n", sequence)

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.45685593 0.11584879 0.39982855]
 [0.19277458 0.7572574  0.83766967]
 [0.17918436 0.97297862 0.16770189]]
Sequence Array:
 [ 0  2  4  6  8 10]


### Vector, Matrix, and Tensor

In [10]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])    #Bahut jada complicated array hota hai toh use tensor kehte hain 
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of array: ", arr.shape)
print("Dimensions of array: ", arr.ndim)
print("Size", arr.size)
print("Data Type: ", arr.dtype)

Shape of array:  (2, 3)
Dimensions of array:  2
Size 6
Data Type:  int64


### Array Reshaping

In [19]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped_arr = arr.reshape((3,4))
print("Reshaped Array: \n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()  #returns copy of the array
print("Flattened Array: ", flattened_arr)

# ravel(returns view, instead of copy like flatten) 
ravelled_arr = reshaped_arr.ravel()
print("Ravelled Array: ", ravelled_arr)

#Transpose
transposed_arr = reshaped_arr.T
print("Transposed Array: \n", transposed_arr)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
