In [1]:
import numpy as np 

In [7]:
arr = np.random.randint(1,21, size=(5,5))
print("Original Array:\n", arr)

arr[:,2] = 1
print("Modified Array:\n", arr)


Original Array:
 [[11  4 14  4 19]
 [19  6 14  5 19]
 [ 3  1 10  2 18]
 [ 6 11  1  1  5]
 [15  1 18 12 17]]
Modified Array:
 [[11  4  1  4 19]
 [19  6  1  5 19]
 [ 3  1  1  2 18]
 [ 6 11  1  1  5]
 [15  1  1 12 17]]


In [14]:
arr = np.arange(1, 17).reshape((4, 4))
print("Original Array:\n", arr)

np.fill_diagonal(arr, 0)
print("Modified Array:\n", arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
